name: default

on:
  push:
  pull_request:

jobs:
  run-container-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run custom Docker container
      run: |
        docker run -v "${GITHUB_WORKSPACE}:/root/.local/share/nvim/lazy/illustrate.nvim" rpapallas/illustrate.nvim:lazy
